### PR TITLE
Add label support

### PR DESCRIPTION
**Pull request by frenck**
Adds support for using labels in targets.

Upstream PR: <https://github.com/home-assistant/core/pull/113753>

### CODE REVIEW

**Review by balloob — APPROVED** [review]

**Comment by frenck** [comment]
Rebased to be up to par with latest greatest, adjusted links in OP.

**Comment by bendikrb** [comment]
Is this still to be considered as a draft? 🤔

**Comment by frenck** [comment]
> Is this still to be considered as a draft? 🤔

Yes. The upstream PR was no longer linked. I've just made a new PR.

**Comment by johntdyer** [comment]
zoolander-will-ferrell

**Pull request merged**
